### ISSUE TITLE
Dúvidas sobre a API do SuperVia

### ISSUE THREAD

**Issue by pitroldev** [nighto/supervia#2]
Olá @nighto,

Estou realizando uma pesquisa e acabei parando nesse seu projeto. Fiquei curioso com a fonte da API mencionada no README. Parece que o endpoint usado para obter as mensagens de áudio, http://webapisupervia.rio.rj.gov.br/api/v1/supervia, está indisponível ou descontinuado. Gostaria de saber, caso possa compartilhar, de onde você o obteve e se há algum novo endpoint ou alternativa para acessar as mensagens de áudio.

Agradeço antecipadamente pela sua ajuda e parabéns pelo projeto!

**Comment by nighto** [comment]
Olá Petro,

Faz um tempo que não mexo nisso, mas me lembro que cheguei nessa API de alguma forma "não oficial", não lembro se foi com algum contato na SuperVia, ou sniffing do app verificando o endpoint que ele se comunicava.

**Comment by pitroldev** [comment]
Obrigado pela resposta, @nighto!

Eu tinha realizado previamente uma engenharia reversa do site e do app, e neles só constam os seguintes endpoints:
- Alertas (voltados para manutenções ou eventos)
- Planeje sua viagem
- Listar Estações/ramais

Mas ainda não encontrei nenhum endpoint próximo ao do repositório, que mostra os avisos sonoros reproduzidos nas estações. :/

De qualquer forma, obrigado pelo apoio! Vou tentar entrar em contato com alguém de lá pra verificar se ainda existe um serviço similar
